FROM golang:alpine AS builder

ARG VERSION=dev

COPY . /src
RUN cd /src && CGO_ENABLED=0 go build \
    -ldflags "-X github.com/rwlove/PUMP/internal/web.Version=${VERSION}" \
    -o /pump-frontend ./cmd/frontend

FROM scratch

WORKDIR /data/PUMP
WORKDIR /app

COPY --from=builder /pump-frontend /app/

ENTRYPOINT ["./pump-frontend"]
